import { useState } from 'react';
import { Arrow } from './PortfolioArrow';

const paths = {
  ETL: { nodes: ['Source files', 'Transform in Spark', '175 result rows'], explanation: 'Compute Query 9 in Spark, then load only the final result into PostgreSQL.', time: '12.81' },
  Hybrid: { nodes: ['Source files', 'Prune columns in Spark', 'Transform with dbt'], explanation: 'Select and cast the required columns in Spark. Load the reduced data, then finish Query 9 in PostgreSQL.', time: '149.60' },
  ELT: { nodes: ['Source files', 'Load raw data', 'Transform with dbt'], explanation: 'Load raw columns through JDBC, then run the transformation inside PostgreSQL.', time: '382.33' },
};
type Architecture = keyof typeof paths;

export default function ResearchProject() {
  const [architecture, setArchitecture] = useState<Architecture>('ETL');
  const selected = paths[architecture];
  return <article className="p-flagship">
    <div className="p-flagship-intro"><h3>Where should the<br />transformation happen?</h3><div><p className="p-project-name">Data Pipeline Research · Undergraduate thesis</p><p>A controlled comparison of ETL, ELT, and Hybrid architectures using TPC-H data. I designed and ran the benchmark to understand how transformation placement affects runtime and resource use.</p><p className="p-context">PySpark · dbt · PostgreSQL · TPC-H</p></div></div>
    <div className="p-research-body"><div className="p-research-explorer"><div className="p-architecture-controls" role="group" aria-label="Explore an architecture">{(Object.keys(paths) as Architecture[]).map(name => <button type="button" key={name} aria-pressed={architecture === name} onClick={() => setArchitecture(name)}>{name}</button>)}</div><div className="p-pipeline" aria-label={`${architecture} pipeline`}>{selected.nodes.map((node, index) => <div key={index}><span>{node}</span>{index < 2 && <Arrow />}</div>)}</div><div className="p-architecture-description" aria-live="polite" aria-atomic="true"><p>{selected.explanation}</p><p className="p-benchmark-number"><strong>{selected.time}<span> s</span></strong><span>Reported runtime<br />Parquet · SF5</span></p></div><p className="p-research-note">One Query 9 workload on one machine. These results describe this setup, not a universal ranking of architectures.</p></div><figure className="p-thesis-figure"><a href="/documents/thesis-defense.pdf#page=11" target="_blank" rel="noopener noreferrer" aria-label="Open the original thesis defense PDF at slide 15"><img src="/images/thesis-runtime.webp" width="1200" height="675" loading="lazy" alt="Original thesis defense slide with the SF5 runtime comparison; all nine values are available in the results disclosure below." /></a><figcaption>From the actual defense deck · slide 15<a href="/documents/thesis-defense.pdf#page=11" target="_blank" rel="noopener noreferrer">Inspect the original <Arrow /></a></figcaption></figure></div>
    <div className="p-research-bottom"><details><summary>Results & test conditions</summary><div className="p-research-details"><p>TPC-H Query 9 · MacBook Air M3, 8 GB RAM · PostgreSQL 18.4 · Spark 4.0.3 · dbt 1.10.22. The deck reports 54 runs across three architectures, three formats, two scales, and three repetitions.</p><table><caption>Reported SF5 runtime in seconds · lower is faster</caption><thead><tr><th scope="col">Method</th><th scope="col">CSV</th><th scope="col">JSONL</th><th scope="col">Parquet</th></tr></thead><tbody>{[['ETL', '32.49', '57.01', '12.81'], ['Hybrid', '193.19', '207.10', '149.60'], ['ELT', '408.26', '451.88', '382.33']].map(row => <tr key={row[0]}><th scope="row">{row[0]}</th>{row.slice(1).map((value, i) => <td key={i}>{value}</td>)}</tr>)}</tbody></table><p>Parquet inputs also differ in column selection between architectures. These results compare complete pipeline designs. Raw per-run measurements are not published in the repository; the values above are transcribed from the defense deck.</p></div></details><a className="p-text-link" href="https://github.com/luthfan-ap/etl-elt-performance-benchmark" target="_blank" rel="noopener noreferrer">Explore the source <Arrow /></a></div>
  </article>;
}
